### PR TITLE
Fix css module ordering

### LINKED ISSUE #41: Styles order for webpack v3
Looks like there is the same issue for this plugin https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/548

I had that issue when I was using extract-text and it was fixed in the new release. However, when I switched to extract-css-chunks that issue appeared again.

### PR DESCRIPTION
**Pull request by jdeal**
Fixes #41.

extract-text-webpack-plugin had this bug: http://bit.ly/2ueFvXt
and was fixed with: http://bit.ly/2hCkpOf

So I borrowed the odering code from there and applied it to this plugin to fix ordering.

### CODE REVIEW

**Comment by mike1808** [comment]
Can you merge this PR?

**Comment by faceyspacey** [comment]
done. should show up automatically on NPM in a bit.

**Comment by faceyspacey** [comment]
thanks @jdeal !

**Comment by jdeal** [comment]
No problem, thanks for merging! Sorry about the tabs/spaces commotion! (Fixed in #43.)

**Comment by Tom910** [comment]
When new release?

**Comment by faceyspacey** [comment]
i didn't realize the commit wasn't properly formatted (with `npm run cm`). So it didn't auto-publish to NPM. Handling it now.

**Comment by faceyspacey** [comment]
published.

**Comment by Tom910** [comment]
Thanks

**Pull request merged**
