### PR TITLE
Escape moduleId and css contents

### LINKED ISSUE #6: Strings need to be escaped in the loader
I'm trying this plugin but I'm having syntax errors on compilation because https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/blob/master/loader.js#L136 and https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/blob/master/loader.js#L137 needs to be escaped (quotes).

Here's some input for you to use in tests:
```
var moduleId = '/Users/andrecruz/Work/moxy/moxy/react-with-moxy-scripts/node_modules/css-loader/index.js?{"modules":true,"sourceMap":true,"importLoaders":1,"camelCase":"dashes","localIdentName":"[name]__[local]___[hash:base64:5]!"}!/Users/andrecruz/Work/moxy/moxy/react-with-moxy-scripts/node_modules/postcss-loader/index.js?{"plugins":[null,null,null,{"version":"5.2.17","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"postcss-cssnext","postcssVersion":"5.2.17"}]}!/Users/andrecruz/Work/moxy/moxy/react-with-moxy/src/pages/error/internal-error/InternalError.css'
```

### PR DESCRIPTION
**Pull request by satazor**
Fixes #6

### CODE REVIEW

**Comment by faceyspacey** [comment]
yea, tests would be good at this point. but let's just keep going for now until we run into trouble. the amount of code i changed from the original is ultimately very little. what was time consuming was simply figuring out how it all worked.

**Comment by faceyspacey** [comment]
...have u tried using this along with `webpack-flush-chunks` and `react-loadable`? 

u tried this yet: https://github.com/faceyspacey/flush-chunks-boilerplate ?

**Comment by satazor** [comment]
I've only read it as well as the PR to react-loadable, I hope that PR lands soon!

I've got it all working on our react-with-moxy project except SSR in pages other than the index. We need to know which chunks belong to a given page, e.g.: /about and add the stylesheets to the rendered html. Though, in order to do that, we need to use react-loadable but the PR needs to land first, correct?

**Comment by faceyspacey** [comment]
NO, it actually doesn't. ...that PR in fact will absorb half the `webpack-flush-chunks` plugin. so in application code you will need to make a slight change. 

...but yea, there is something a bit different from the `webpack-flush-chunks` docs. There is no `flushRequires` method yet in `react-loadable`. There are 2 methods instead: one for babel and one for webpack. Check the boilerplate and you will see I don't follow the preemptive documentation and instead toggle between the 2 methods. 

Copy the boilerplate (specifically the `server/render.js` file) and you're good to go with RL as it is now.

**Comment by satazor** [comment]
Thanks for the info, I evaluate the boilerplate and try to set it up.

**Pull request merged**
