### PR TITLE
Added option to skip creation of .no_css.js chunks

### PR DESCRIPTION
**Pull request by Igogrek**
Thanks for the plugin - it works great (we were finally able to fix this issue with extract-text-plugin).
But in our project we don't need the .no_css.js chunks and I've added an option to skip creation of them.

### CODE REVIEW

**Comment by faceyspacey** [comment]
Thanks for this. It's a solid idea. I'll merge it. Just give me a day or 2 to marinate on the option name before committing to it.

**Comment by Igogrek** [comment]
You're probably right. Will **noCssChunks** with default value of true be better instead?

**Comment by faceyspacey** [comment]
yea that's the sorta stuff in my head. ...now we just gotta figure out if we can come up with a word that only has 2 camel humps or even one.

**Comment by Igogrek** [comment]
So, any thoughts on how the option should be named after all?

**Comment by faceyspacey** [comment]
2.0 is out!

check this:
https://medium.com/faceyspacey/webpacks-import-will-soon-fetch-js-css-here-s-how-you-do-it-today-4eb5b4929852

and this
https://github.com/faceyspacey/babel-plugin-dual-import

and the readme to this package is updated.

The short story is the problem is solved in a different way now, which involves only no_css chunks + css. The babel plugin will import both a js + css file! Let me know what you think.

**Pull request closed without merging**
