### PR TITLE
fix: hmr issue where base64 links would cause loader to fail

### PR DESCRIPTION
**Pull request by ScriptedAlchemy**
fix: hmr asset order fixed, updates cascade correctly

### CODE REVIEW

**Comment by hamczu** [comment]
Why was "webpack-external-import" added here? I'm asking because:
- it's not used anywhere?
- webpack-external-import has react and redux as peer dependency
- doesn't look stable nor actively developed

**Comment by tanhauhau** [comment]
@hamczu I was wondering that too and ended up in this PR. 🤔

**Comment by ScriptedAlchemy** [comment]
extract-css-chunks-webpack-plugin@4.7.2-mit
 if you want without external-import

**Pull request merged**
